# Generated by Django 4.2.7 on 2023-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('num', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('emails', models.ManyToManyField(to='scrapper.email')),
                ('phone_numbers', models.ManyToManyField(to='scrapper.phonenumber')),
                ('sites', models.ManyToManyField(to='scrapper.site')),
            ],
        ),
    ]
